export {};
/**
 * LESSON 13
 * Utility Types
 * 
 * Goal:
 * Learn how to transform existing types using Partial, Required, Readonly, Pick, Omit, and Record.
 * 
 * How to run:
 * npm run lesson:13
 */

console.log('lesson 13-utility-types');

/**
 * Utility types are built-in tools that help you construct new types 
 * from existing ones without rewriting everything.
 */

/**
 * BASIC EXAMPLE
 */
interface User {
    id: number;
    name: string;
    email: string;
}

type UserUpdate = Partial<User>; // All properties become optional
type UserPreview = Pick<User, "id" | "name">; // Only id and name
type UserWithoutEmail = Omit<User, "email">; // Everything except email

/**
 * FRONTEND EXAMPLE
 * Utility types are essential for creating flexible UI components and Forms.
 * Partial is used in form updates, Omit is used to strip out internal IDs before sending to an API.
 */
interface UserAccount {
    id: string;
    email: string;
    displayName: string;
    avatarBase64: string;
}

// 1. Form Update State (Partial)
// When a user updates their profile, they might only change the displayName
type UpdateProfileForm = Partial<UserAccount>;
const profileEdits: UpdateProfileForm = { displayName: "MechSeiko" };

// 2. Creating New Entity (Omit)
// When creating a user, the ID is generated by the server, so we omit it from the payload
type CreateUserPayload = Omit<UserAccount, "id">;
const newUserPayload: CreateUserPayload = {
    email: "test@example.com",
    displayName: "Test",
    avatarBase64: "data:image/png;base64,..."
};

// 3. UI Theme Dictionary (Record)
const themeColors: Record<"light" | "dark", string> = {
    light: "#FFFFFF",
    dark: "#1A1A1A"
};

/**
 * COMMON MISTAKES
 */
type ReadonlyUser = Readonly<User>;
const user: ReadonlyUser = { id: 1, name: "A", email: "a@a.com" };
// user.name = "B"; // ❌ Error: Cannot assign to 'name' because it is a read-only property.

/**
 * PRACTICE CHALLENGES
 */

// 1. Create a 'Partial' version of a 'Product' interface.


// 2. Use 'Pick' to create a 'ContactInfo' type from a 'User' interface (email and phone).


// 3. Create a 'Record' that maps category names (strings) to arrays of product names.



/**
 * --- SOLUTIONS ---
 */
// 1. type PartialProduct = Partial<Product>;
// 2. type ContactInfo = Pick<User, "email" | "phone">;
// 3. type CategoryMap = Record<string, string[]>;
